require("user.launch")
require("user.settings")
require("user.keymaps")
require("user.autocmds")
require("user.orgexport")

SPEC("user.colorschemes.tokyonight")

SPEC("user.alpha")
SPEC("user.comment")
SPEC("user.completion")
SPEC("user.conform")
SPEC("user.debug")
SPEC("user.diffview")
SPEC("user.fugitive")
SPEC("user.gitsigns")
SPEC("user.harpoon")
SPEC("user.lsp-nvim")
SPEC("user.mini")
SPEC("user.neogit")
SPEC("user.oil")
SPEC("user.orgmode")
SPEC("user.quarto")
SPEC("user.sleuth")
SPEC("user.slime")
SPEC("user.vim-table-mode")
SPEC("user.telescope")
SPEC("user.todo-comments")
SPEC("user.treesitter")
SPEC("user.trouble")
SPEC("user.undotree")
SPEC("user.venv_selector")
SPEC("user.whichkey")
SPEC("user.zen")
SPEC("user.slime")

require("user.lazy")
